// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/ebt.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1543572403214441030),
      name: 'EBT',
      lastPropertyId: const obx_int.IdUid(6, 3544159127052456062),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 454382992019635814),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8788927444672195486),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2948420963988613879),
            name: 'fraction',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5457758441566327167),
            name: 'dosePerFraction',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3962348039644537347),
            name: 'bedValue',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3544159127052456062),
            name: 'eqd2Value',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 1543572403214441030),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    EBT: obx_int.EntityDefinition<EBT>(
        model: _entities[0],
        toOneRelations: (EBT object) => [],
        toManyRelations: (EBT object) => {},
        getId: (EBT object) => object.id,
        setId: (EBT object, int id) {
          object.id = id;
        },
        objectToFB: (EBT object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addFloat64(2, object.fraction);
          fbb.addFloat64(3, object.dosePerFraction);
          fbb.addFloat64(4, object.bedValue);
          fbb.addFloat64(5, object.eqd2Value);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final fractionParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final dosePerFractionParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final bedValueParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final eqd2ValueParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final object = EBT(
              id: idParam,
              name: nameParam,
              fraction: fractionParam,
              dosePerFraction: dosePerFractionParam,
              bedValue: bedValueParam,
              eqd2Value: eqd2ValueParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EBT] entity fields to define ObjectBox queries.
class EBT_ {
  /// See [EBT.id].
  static final id = obx.QueryIntegerProperty<EBT>(_entities[0].properties[0]);

  /// See [EBT.name].
  static final name = obx.QueryStringProperty<EBT>(_entities[0].properties[1]);

  /// See [EBT.fraction].
  static final fraction =
      obx.QueryDoubleProperty<EBT>(_entities[0].properties[2]);

  /// See [EBT.dosePerFraction].
  static final dosePerFraction =
      obx.QueryDoubleProperty<EBT>(_entities[0].properties[3]);

  /// See [EBT.bedValue].
  static final bedValue =
      obx.QueryDoubleProperty<EBT>(_entities[0].properties[4]);

  /// See [EBT.eqd2Value].
  static final eqd2Value =
      obx.QueryDoubleProperty<EBT>(_entities[0].properties[5]);
}
